### ISSUE TITLE
missing some dependencies

### ISSUE THREAD

**Issue by daoran** [devanshdhrafani/diff_drive_bot#1]
sudo apt install ros-melodic-turtlebot3-gazebo
sudo apt-get install ros-melodic-amcl
sudo apt install ros-melodic-move-base

**Comment by devanshdhrafani** [comment]
Can you check if 
`rosdep install --from-paths src --ignore-src -r -y
`
solves the issue?

**Comment by daoran** [comment]
To use `rosdep`, have to add the following inside `package.xml` file.

```xml
  <depend>amcl</depend>
  <depend>turtlebot3_gazebo</depend>
  <depend>move_base</depend>
```
